name: Deploy
on:
  release:
    types: [published]
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [lab4*]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: course.prafdin.ru
          username: kali
          port: 3126
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/kali/catty-reminders-app
            
            git fetch origin
            git checkout lab4
            git pull origin lab4 || true
            
            OWNER=$(echo "avofl1ow" | tr "[:upper:]" "[:lower:]")
            
            # Чистый вынос конфигурации в .env файл (Замечание Данилы выполнено)
            echo "IMAGE=ghcr.io/$OWNER/catty-reminders-app:${{ github.event.workflow_run.head_sha || github.sha }}" > .env
            echo "APP_CONTAINER_NAME=catty-app" >> .env
            echo "DB_CONTAINER_NAME=catty-db" >> .env
            echo "MARIADB_ROOT_PASSWORD=mypass" >> .env
            echo "MARIADB_PASSWORD=mypass" >> .env
            echo "MARIADB_USER=root" >> .env
            echo "MARIADB_DATABASE=catty_reminders" >> .env
            echo "HOST_DB_PORT=3306" >> .env
            echo "CONTAINER_DB_PORT=3306" >> .env
            echo "HOST_APP_PORT=8181" >> .env
            echo "CONTAINER_APP_PORT=8181" >> .env

            echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u avofl1ow --password-stdin
            sudo docker compose down --remove-orphans || true
            sudo docker compose pull
            sudo docker compose up -d --force-recreate
